### ISSUE TITLE
Missing support for HttpMock?

### ISSUE THREAD

**Issue by latacora-tomekr** [henribru/google-api-python-client-stubs#2]
Hi, thanks for the work on this library!

The google-api-python-client library makes available the `HttpMock` class for testing purposes (see https://github.com/googleapis/google-api-python-client/blob/master/docs/mocks.md#example)

I don't believe this is compatible with the signature defined at https://github.com/henribru/google-api-python-client-stubs/blob/master/googleapiclient-stubs/discovery.pyi#L346.

Would an `|` operator on the types be the change we want here or would you recommend doing something like:

```
http = Http(HttpMock("test_response.json", {"status": "200"}))
```

**Comment by henribru** [comment]
Thanks for pointing out this issue. A union type, as you suggest, would work, although I'm wondering if a protocol type might be more appropriate in this case. I'll try to take a look at it this weekend.

**Comment by henribru** [comment]
I've published a new version now with your suggestion of using a union. I might change it to a protocol at a later point, if it's backwards compatible, but this should fix your issue. Thanks again for pointing it out.
