### ISSUE TITLE
Stubs for testing?

### ISSUE THREAD

**Issue by emfdavid** [henribru/google-api-python-client-stubs#24]
Could this library be extended to provide stubbing for tests?
I have recently started developing against GCP in python and I really miss the [AWS SDK test stubs](https://aws.amazon.com/blogs/developer/advanced-client-stubbing-in-the-aws-sdk-for-ruby-version-3/) for Ruby.
If this feels like a good fit, I would be interested in collaborating.

**Comment by henribru** [comment]
While I'm sure that would be a useful feature, unfortunately I don't find it to be a good fit for this project, since it's only meant to provide type annotation stub files and has no runtime functionality.

**Comment by emfdavid** [comment]
Got it - thanks for your work.
