### ISSUE TITLE
Update for 2.64?

### ISSUE THREAD

**Issue by SimonSchick** [henribru/google-api-python-client-stubs#25]
My understanding is that these types are auto-generator, can you perform an update and/or publish the generator so this can be done automatically?

**Comment by henribru** [comment]
Fixed in v1.12.0 https://github.com/henribru/google-api-python-client-stubs/releases/tag/v1.12.0

**Comment by SimonSchick** [comment]
Amazing, as far as tips for automation, you might be able to simply use a scheduled github action, check if there have been changes and publish them accordingly.
