### ISSUE TITLE
_media methods are missing from stubs

### ISSUE THREAD

**Issue by kbehlers** [henribru/google-api-python-client-stubs#28]
Similar to https://github.com/henribru/google-api-python-client-stubs/issues/12

There are methods like `get_media` and `watch_media` that are missing from the stubs

https://github.com/googleapis/google-api-python-client/blob/d0f8a05b5c236f99d88fc6e0ef671a0a3eb58a4b/googleapiclient/discovery.py#L1471-L1479

See also:

- https://developers.google.com/resources/api-libraries/documentation/drive/v3/python/latest/drive_v3.files.html
- https://googleapis.github.io/google-api-python-client/docs/dyn/drive_v3.files.html
- https://github.com/googleapis/google-api-python-client/blob/e4faf093d059688eb1a57689c2ac79563b61eaf5/docs/dyn/drive_v3.files.html

**Comment by henribru** [comment]
Thanks for pointing this out. I can look into adding these, though it probably won't happen during Christmas

**Comment by kbehlers** [comment]
@henribru Thank you! I appreciate your work on the package.

**Comment by henribru** [comment]
Had some extra time to look at it and it turned out to be a simple change to generate these. Fixed in https://github.com/henribru/google-api-python-client-stubs/releases/tag/v1.14.0

**Comment by henribru** [comment]
I was mislead by https://github.com/googleapis/google-api-python-client/blob/main/googleapiclient/model.py#L329-L331 returning a string (probably a bug) instead of bytes and so initially used string as the return type, but that's fixed in https://github.com/henribru/google-api-python-client-stubs/releases/tag/v1.14.1

**Comment by kbehlers** [comment]
@henribru Amazing! Thank you again 🙏 I downloaded and it resolved the type error as hoped
