### ISSUE TITLE
Which version for google-api-python-client v1.12.11 ?

### ISSUE THREAD

**Issue by benbuckman** [henribru/google-api-python-client-stubs#38]
Hi,
First, thanks for maintaining this library.
I'm using `google-api-python-client` `v1.12.11` in tandem with Airflow 2.6.1's [constraints file](https://github.com/apache/airflow/blob/constraints-2.6.1/constraints-3.10.txt#L268).

I'm trying to install `google-api-python-client-stubs` to match, but not finding any version that `pip` is happy with.

If I try `google-api-python-client-stubs==1.12.0` I get,
```
google-api-python-client-stubs 1.12.0 depends on google-api-python-client<3.0.0 and >=2.64.0
The user requested (constraint) google-api-python-client==1.12.11
```

and if I just specify ``google-api-python-client-stubs` in `requirements.txt` and let pip try to figure it out, it tries all the available releases and ends with,
```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Please advise.
Thank you!

**Comment by henribru** [comment]
> If I try google-api-python-client-stubs==1.12.0 I get,

Oh, and note that the stubs are versioned independently from the library, so v1.12.0 was for v2.64.0 for example. I usually mention the version compatibility in the release notes, it can also be seen in `pyproject.toml`

**Comment by henribru** [comment]
Closing since there was no follow-up, but feel free to let me know if you're still having issues
