### ISSUE TITLE
Missing apikeys.googleapis.com stubs

### ISSUE THREAD

**Issue by linuxdaemon** [henribru/google-api-python-client-stubs#6]
https://cloud.google.com/api-keys/docs/reference/rest

**Comment by henribru** [comment]
I'll try to do a release this weekend which should add any APIs currently present in https://github.com/googleapis/google-api-python-client/tree/master/googleapiclient/discovery_cache/documents that are missing stubs

**Comment by henribru** [comment]
Just released a new version containing this API!
